CREATE TABLE IF NOT EXISTS insumos(
    id_insumo INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descripcion TEXT NOT NULL,
    stock INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    id_categoria_insumo INTEGER NOT NULL,
    id_usuario_registro INTEGER NOT NULL,
    fecha_registro DATE NOT NULL,
    id_usuario_edicion INTEGER,
    fecha_edicion DATE,
    activo INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS insumos_producto(
    id_insumos_producto INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_insumo INTEGER REFERENCES insumos(id_insumo),
    id_producto INTEGER,
    cantidad INTEGER NOT NULL,
    id_usuario_registro INTEGER NOT NULL,
    fecha_registro DATE NOT NULL,
    id_usuario_edicion INTEGER,
    fecha_edicion DATE,
    activo INTEGER NOT NULL
)
CREATE TABLE IF NOT EXISTS compras (
    id_compra INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_estatus_compra INTEGER REFERENCES estatus_compra(id_estatus_compra),
    total INTEGER NOT NULL,
    total_productos INTEGER NOT NULL,
    id_usuario_registro INTEGER NOT NULL,
    fecha_registro DATE NOT NULL,
    id_usuario_edicion INTEGER,
    fecha_edicion DATE,
    activo INTEGER NOT NULL
)
CREATE TABLE IF NOT EXISTS estatus_compra(
    id_estatus_compra INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descripcion TEXT NOT NULL,
    id_usuario_registro INTEGER NOT NULL,
    fecha_registro DATE NOT NULL,
    id_usuario_edicion INTEGER,
    fecha_edicion DATE,
    activo INTEGER NOT NULL
)
CREATE TABLE IFNOT EXISTS detalle_compra(
    id_detalle_compra INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_insumo INTEGER REFERENCES insumos(id_insumo),
    precio INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha DATE NOT NULL,
    cantidad_real INTEGER NOT NULL,
    id_usuario_registro INTEGER NOT NULL,
    fecha_registro DATE NOT NULL,
    id_usuario_edicion INTEGER,
    fecha_edicion DATE,
    activo INTEGER NOT NULL
)